env:
  sources:
    - kind: dodal
      module: dodal.beamlines.aithre
    - kind: planFunctions
      module: mx_bluesky.beamlines.aithre_lasershaping

stomp:
  host: localhost
  port: 61613
  auth:
    username: guest
    password: guest