[project]
name = "aithre"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["pyqt5",
		"opencv-python",
		"numpy",
		"requests",
		"zmq",
		"asyncio",
		"httpx",
		"qasync",
		"ruff",
]
[tool.setuptools]
py-modules = []